language: node_js
node_js:
- 11.0.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
services:
- docker
env:
  global: 
install:
- npm install
script:
- npm run
deploy:
  provider: heroku
  api_key:
    secure: sPDD+ZJdL/ql5pTqNH+4LuKgUSvoChhcV5HYpQFZWlyJOr0fzU08kUC6YzQVzaWPQHaUx5As7kcxOzySN+38ESk2XwxBP1Fu+5B4BtwO0zuouoEX9+AE+yaDHVDZB9A1jksM+Uv5Cvr/awKKdJT4pEUlEJ1WNqKH3jaAA9QMV63O6a3bJzuLnsTW0RrxxpYTuHfs1uL9/O9ctlazLZQDnfN1iNEVP8bDWgqnspUIt9+IKLM+aSduueWfR5ph1Q39tRCkGk66tMjS3U85iD4WCP5m9okK0MVpHLvlgNpMURc/lytQZEHHHyKA1AADo7j2lLvb3JXpxhPLMF0HAJlsjZwwpilw/9+g/TYkp635jAL0Bbt2qIlx1em/LecsrKdNWoRbvi0ibOtGnSAcKyDn5ym2D5GNpKBLl+1CYCGevkZdgN761bcaF8pAXtoi0ksafgvxPZWSu4HO5hFB10XP1/zhg5Ik7Fke4KTGrBox3XoW3XcOBnPUtOvJsc1xEn835zhwiza1+4AIEGLvrshhNZosCffwiOYlf2YYrkcrgKIxueYcxD2y7CaMXcJbEMYQthBBMwJDlUT8VWzdksefwx6YtktKLTwqTeLzYNX/Rgmb6qjtLzTx2fsm1OlII8Qbseo4yJPdntE1Q/eocCrj9NBZJfl8tQ1spQz0XWi60XQ=
  app: nodegeo
  strategy: git
  on:
    branch:
    - master
    repo: lebedajaromir/nodeGEO
